stages:
  - build
build-code-job:
  tags:
    - now
  stage: build
  script:
    - echo "Start build cat and grep"
      #    - make
      # artifacts:
      #paths:
      #- s21_cat
      #- s21_grep
      #expire_in: 1 month
