stages:
  - style
  - build
  - test
  - deploy
style-check:
  tags:
    - now
  stage: style
  script:
    - cp materials/linters/.clang-format src/cat
    - cp materials/linters/.clang-format src/grep
    - clang-format -n src/cat/*.c src/grep/*.c
    - ./style_fail.sh;
build-code-job:
  tags:
    - now
  stage: build
  script:
    - echo "Start build cat and grep"
    - cd src/cat; make s21_cat;
    - cd ../grep; make s21_grep;
    - ls -a; ls -a ../../;
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 1 month
test-code-job:
  tags:
    - now
  stage: test
  dependencies:
    - build-code-job
  script:
    - ls -a; ls -a ./src/cat/;
    - ./score_fail.sh
deploy-code-job:
  tags:
    - now
  stage: deploy
  before_script:
    - ID=$(cat id_rsa)
    - eval $(ssh-agent -s)
    - echo "$ID" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -p22 -o stricthostkeychecking=no -o userknownhostsfile=/dev/null ./src/cat/s21_cat provemen_deploy@10.20.0.20:/home/provemen_deploy
    - scp -p22 -o stricthostkeychecking=no -o userknownhostsfile=/dev/null ./src/grep/s21_grep provemen_deploy@10.20.0.20:/home/provemen_deploy
    - ssh -p22 provemen_deploy@10.20.0.20 "echo -e "kidalovo" | sudo -S mv s21* /usr/local/bin"
  when: manual
