stages:
  - style
  - build
  - test
  - deploy
  - notify
style-check:
  tags:
    - now
  stage: style
  script:
    - cp materials/linters/.clang-format src/cat
    - cp materials/linters/.clang-format src/grep
    - clang-format -n src/cat/*.c src/grep/*.c
    - ./style_fail.sh;
    - ./tg_msg.sh PASSED
build-code-job:
  tags:
    - now
  stage: build
  script:
    - echo "Start build cat and grep"
    - cd src/cat; make s21_cat;
    - cd ../grep; make s21_grep;
    - ../../tg_msg.sh PASSED
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 1 month
test-code-job:
  tags:
    - now
  stage: test
  dependencies:
    - build-code-job
  script:
    - ./score_fail.sh
    - ./tg_msg.sh PASSED
deploy-code-job:
  tags:
    - now
  stage: deploy
  before_script:
    - ID=$(cat id_rsa)
    - eval $(ssh-agent -s)
    - echo "$ID" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ./ssh_scr.sh
    - ./tg_msg.sh PASSED
  when: manual
notify-error:
  tags:
    - now
  stage: notify
  script:
    - ./tg_msg.sh FAIL
  when: on_failure
