stages:
  - build
build-code-job:
  tags:
    - now
  stage: build
  script:
    - echo "Start build cat and grep"
    - cd src/cat; make s21_cat;
    - cd ../grep; make s21_grep;
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 1 month
