stages:
  - style
  - build
  - test
style-check:
  tags:
    - now
  stage: style
  script:
    - cp materials/linters/.clang-format src/cat
    - cp materials/linters/.clang-format src/grep
    - clang-format -n src/cat/*.c src/grep/*.c
    - ./style_fail.sh;
build-code-job:
  tags:
    - now
  stage: build
  script:
    - echo "Start build cat and grep"
    - cd src/cat; make s21_cat;
    - cd ../grep; make s21_grep;
    - ls -a; ls -a ../../;
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 1 month
test-code-job:
  tags:
    - now
  stage: test
  dependencies:
    - build-code-job
  script:
    - ls -a; ls -a ./src/cat/;
    - ./score_fail.sh
